include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - require_trailing_commas
    - prefer_final_locals
    - avoid_unnecessary_containers

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
